services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=rhexpress'
      - 'MYSQL_ROOT_PASSWORD=aluno1234' # Define a senha do usuário root
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql # Garante que os dados não sumam ao reiniciar

volumes:
  mysql_data:
