services:
  postgres:
    image: 'postgres:17'
    environment:
      POSTGRES_DB: acheimontador
      POSTGRES_USER: ${DB_USERNAME:-acheimontador}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-acheimontador}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
